project:
  type: website

website:
  title: "Kate Esbenshade"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "Dashboard"
        href: dashboard.html
      - text: "Websites"
        href: websites.html
    tools:
      - icon: github
        href: https://github.com/stanford-brand-yml/quarto-branded-website

format:
  html:
    toc: true
    theme:
      - brand

# Use the brand file for all documents in the project
brand: _brand.yml
