project:
  type: website

website:
  title: "Kate Esbenshade"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "Blog"
        href: dashboard.html
      - text: "Websites"
        href: websites.html
    tools:
      - icon: github
        href: https://github.com/kate-esbenshade
      - icon: linkedin
        href: https://www.linkedin.com/in/kate-esbenshade-2b158418b/
      - icon: envelope
        href: mailto:ksesben@stanford.edu
      

format:
  html:
    toc: true
    theme:
      - brand

# Use the brand file for all documents in the project
brand: _brand.yml
